name: ${project.name}
main: de.redstoneworld.redinteract.RedInteract
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   redinteract:
      aliases: [ri]
      description: Command description.
      usage: /<command> reload|nearby|(add|remove) [<world> <x> <y> <z>]
      permission: rwm.redinteract.command
      permission-message: You don't have the permission <permission>
permissions:
   rwm.redinteract.command:
      description: Gives permission to the plugin command
      default: op
   rwm.redinteract.command.add:
      description: Gives permission to add new locations
      default: op
   rwm.redinteract.command.remove:
      description: Gives permission to remove registered locations
      default: op
   rwm.redinteract.command.nearby:
      description: Gives permission to get nearby locations
      default: op
   rwm.redinteract.command.reload:
      description: Gives permission to reload the plugin
      default: op
